if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

shopt -s histappend
PROMPT_COMMAND='history -a;history -n'
export HISTFILESIZE=400000000
export HISTSIZE=10000
export HISTTIMEFORMAT="%d/%m/%y %T "

readonly PROMPT_COMMAND
readonly HISTFILE
readonly HISTFILESIZE
readonly HISTSIZE
readonly HISTCMD
readonly HISTCONTROL
readonly HISTIGNORE
readonly HISTTIMEFORMAT